import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";

const roboto = Montserrat({ subsets: ["latin"], weight:['400','700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
